/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.omadi.camera;

import java.util.HashMap;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.KrollObject;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiContext;

import android.content.Intent;


@Kroll.module(name="Customcamera", id="com.omadi.camera")
public class CustomcameraModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "CustomcameraModule";
	private static final boolean DBG = TiConfig.LOGD;
	static KrollFunction imageCallback;
	static Object eve;
	
	private static CustomcameraModule _instance;

	  public static CustomcameraModule getInstance()
	  {
	    return _instance;
	  }

	  public CustomcameraModule(TiContext tiContext)
	  {
	    super(tiContext);
	    _instance = this;
	  }


	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public CustomcameraModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public void openCamera(KrollDict options)
	{
		eve = (Object) options.get("event");
		imageCallback = (KrollFunction)options.get("callbackFnc");
		
		Intent i = new Intent(this.getActivity(), DgCamActivity.class);
		this.getActivity().startActivity(i);
	}
	
	// Properties
	@Kroll.getProperty
	public String getExampleProp()
	{
		Log.d(LCAT, "get example property");
		return "hello world";
	}
	
	
	@Kroll.setProperty
	public void setExampleProp(String value) {
		Log.d(LCAT, "set example property: " + value);
	}

}

